name: "daily update"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Initialize
      run: |
        sudo apt install git -y
        rm -rf infrared
        rm -rf nfc
        rm -rf subghz
        rm -rf badusb
        mkdir -p infrared
        mkdir -p nfc
        mkdir -p subghz
        mkdir -p badusb
    - name: logickworkshop/Flipper-IRDB
      run: |
        cd infrared
        wget -nv https://github.com/logickworkshop/Flipper-IRDB/archive/refs/heads/main.zip
        unzip -qq main.zip
        rm -rf main.zip
        mv Flipper-IRDB-main/* ./
    - name: Gioman101/FlipperAmiibo
      run: |
        cd nfc
        wget -nv https://github.com/Gioman101/FlipperAmiibo/archive/refs/heads/main.zip
        unzip -qq main.zip
        rm -rf main.zip
        mv FlipperAmiibo-main amiibo
    - name: UberGuidoZ/Flipper
      run: |
        mkdir temp
        cd temp
        wget -nv https://github.com/UberGuidoZ/Flipper/archive/refs/heads/main.zip
        unzip -qq main.zip
        mkdir ../subghz/vehicles/
        cp -R Flipper-main/Sub-GHz/Vehicles/* ../subghz/vehicles/
        mkdir ../subghz/restaurant_pagers/
        cp -R Flipper-main/Sub-GHz/Restaurant_Pagers/* ../subghz/restaurant_pagers/
        mkdir ../nfc/fun_files/
        cp -R Flipper-main/NFC/Fun_Files/* ../nfc/fun_files/
        cd ..
        rm -rf temp
    - name: Kavitate/FlipperZeroBadUSB
      run: |
        mkdir temp
        cd temp
        wget -nv https://github.com/Kavitate/FlipperZeroBadUSB/archive/refs/heads/main.zip
        unzip -qq main.zip
        mkdir ../badusb/prank/
        cp -R FlipperZeroBadUSB-main/Prank/* ../badusb/prank/
        cd ..
        rm -rf temp
    - name: Clear
      run: |
        find ./infrared ! -name "*.ir" -type f -delete
        find ./nfc ! -name "*.nfc" -type f -delete
        find ./subghz -not -name "*.sub" -a -not -name "*.raw" -type f -delete
        find ./badusb ! -name "*.txt" -type f -delete
    - name: Commit changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "automated"
        branch: "master"
        author_name: "Enz0Z"
        author_email: "enz0z@users.noreply.github.com"
